apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-db
  labels:
    app: accounts-db
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: accounts-db
  template:
    metadata:
      labels:
        app: accounts-db
    spec:
{{- if .Values.dockerregistry.enabled }}
      imagePullSecrets:
        - name: docker-registry-secret
{{- end }}
      containers:
        - name: accounts-db
          image: {{ .Values.db.image }}:{{ .Values.db.tag }}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-data
          ports:
            - name: db-port
              containerPort: {{ .Values.db.containerPort }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret }}
                  key: db-pass
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pv-claim
      initContainers:
        - name: cleanup-mysql
          image: busybox
          command:
            - sh
            - -c
            - |
              rm -rf /var/lib/mysql/lost+found
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
