apiVersion: v1
kind: Service
metadata:
  name: accounts-app-service
spec:
  ports:
    - port: {{ .Values.app.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.app.containerPort }}
  selector:
    app: accounts-app
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-db
spec:
  ports:
    - port: {{ .Values.db.servicePort }}
      targetPort: db-port
      protocol: TCP
  selector:
    app: accounts-db
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-cache
spec:
  ports:
    - port: {{ .Values.memcached.servicePort }}
      targetPort: cache-port
      protocol: TCP
  selector:
    app: accounts-cache
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-mq
spec:
  ports:
    - port: {{ .Values.rabbitmq.servicePort }}
      targetPort: mq-port
      protocol: TCP
  selector:
    app: accounts-mq
  type: ClusterIP
